### ISSUE TITLE
Openframeworks version to compile this solution?

### ISSUE THREAD

**Issue by leefeel** [nama-gatsuo/GenerativeNature#1]
Hello,

I would love to try out this solution and work with ofxDeferredShading. Will it compile with oF10.1 ? I'm working on Windows 10, Visual Studio 2017.

If not, which version of openframeworks and VS should I use?

Thank you!

**Comment by leefeel** [comment]
So, I decided to give a try. I downloaded the project, and ofxDeferredShading branch:latest-Of. It just give me one error:

Error	C2039	'xyz': is not a member of 'glm::tvec4<float,0>'	GenerativeNature	c:\users\ivang\of_v0.10.1_vs2017\addons\ofxdeferredshading\src\shadowlightpass.cpp	97	

If I comment this line, the rest of the project compile perfectly.

How can I solve this? Thank you so much
